apiVersion: batch/v1
kind: Job
metadata:
  name: post-deployment-hook
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  ttlSecondsAfterFinished: 5
  template:
    metadata:
      name: post-deployment-hook
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: docker.imanage.com/busybox:1.32.0
        command: ['sh', '-c', 'wget http://helloworld:8080/hello/bootstrap -O /dev/null -q']